name: Build and Push to GCR

on:
 workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }} 
#  GKE_KEY: ${{ secrets.GKE_KEY }} 
env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  REGISTRY_HOSTNAME: gcr.io


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCR_KEY }}'

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
          gcloud auth configure-docker us-east1-docker.pkg.dev

    # Build the Docker image
    - name: Build
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo $TAG
        docker build -t us-east1-docker.pkg.dev/gke-panji/docker-panji/reactgit:latest .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo $TAG
        docker push us-east1-docker.pkg.dev/gke-panji/docker-panji/reactgit:latest
        gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project gke-panji
        helm install reactjs springboot
